services:
  frontend:
    image: cios-frontend
    container_name: cios-frontend-dev
    build:
      context: .
      dockerfile: .docker/dockerfile.frontend
      args:
        - BACKEND_URL=wss://ws.cioschat.com
    ports:
      - 3000:80

  backend:
    image: cios-backend
    container_name: cios-backend-dev
    build:
      context: .
      dockerfile: .docker/dockerfile.backend
    environment:
      - PORT=80
    ports:
      - 4000:80