services:
  frontend:
    image: ghcr.io/thedokt0r/chatroom-frontend:latest
    container_name: chatroom-frontend
    ports:
      - 3000:80

  backend:
    image: ghcr.io/thedokt0r/chatroom-backend:latest
    container_name: chatroom-backend
    ports:
      - 4000:80