FROM oven/bun:latest AS build
WORKDIR /app
COPY . .
RUN bun i --frozen-lockfile
WORKDIR /app/packages/frontend
RUN bun run build

FROM nginx:1.28-alpine-slim AS base
COPY --from=build /app/packages/frontend/dist /usr/share/nginx/html
COPY nginx/frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80